apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: cli-main-ci
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtap-contract-tenant/ec-main-ci/cli-main-ci@sha256:7d6110ecec31a36ff1bfcc45db78c2d37e16414d2317dac247057599c892668a
        name: container-image
        resources: {}
status: {}
