apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: cli-main-ci
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtap-contract-tenant/ec-main-ci/cli-main-ci@sha256:4cd15a8e12ae528a733bc77c0bbf55a8de7d1bbc07f97ea628d948cb0faeaeda
        name: container-image
        resources: {}
status: {}
