apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: cli-main-ci
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtap-contract-tenant/ec-main-ci/cli-main-ci@sha256:eea62a82041743619085cf36f1b43436dccaa63c15c6843d7f88edfc94767bd2
        name: container-image
        resources: {}
status: {}
