apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: cli-main-ci
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtap-contract-tenant/ec-main-ci/cli-main-ci@sha256:268e73d1191339e54753c669216cc6bc1052e3f55b8de724532718e337498bfc
        name: container-image
        resources: {}
status: {}
