apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: cli-main-ci
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtap-contract-tenant/ec-main-ci/cli-main-ci@sha256:292cb9571fb79e96af798601d50f3bb5cf0cea93a4de0b16ffd8161873becec8
        name: container-image
        resources: {}
status: {}
