apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: cli-main-ci
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: cli-main-ci
    app.kubernetes.io/part-of: ec-main-ci
  name: cli-main-cinxm3
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: cli-main-ci
    weight: 100
status: {}
